### ISSUE TITLE
Fourier Elimination

### ISSUE THREAD

**Issue by fwieder** [mcmtroffaes/pycddlib#38]
Hi everyone!
I was wondering whether the dd_FourierElimination and dd_BlockElimination functions from the cddlib have been exposed yet. I want to use these functions to determine projections of polyhedra in halfspace representation. I can not find the functions in the documentation for pycddlib. If they have not been exposed yet, is there a reason not to do it? I could try to help exposing them, but it would probably take me a while, since i have no experience with something like that. 
Thanks!

**Comment by mcmtroffaes** [comment]
I guess nobody has needed them yet. Happy to take a patch to add them to the interface.

**Comment by fwieder** [comment]
Thank you for your reply. I will see what i can do :)

**Comment by Edenharder** [comment]
> I guess nobody has needed them yet. Happy to take a patch to add them to the interface.

I'm one of nobodies ;P

**Comment by mcmtroffaes** [comment]
I've added this now. It's included with the 3.0.0b1 release (in beta since there are a lot of API changes, necessary to support type hints):

https://pypi.org/project/pycddlib/3.0.0b1/#files

Documentation:

https://pycddlib.readthedocs.io/en/latest/cdd.html#cdd.fourier_elimination
https://pycddlib.readthedocs.io/en/latest/cdd.html#cdd.block_elimination
