### ISSUE TITLE
Error building pycddlib from source on Windows 11 with Python 3.13.0

### ISSUE THREAD

**Issue by Tamysam** [mcmtroffaes/pycddlib#76]
Hi,
I’m trying to install pycddlib on Windows 11 (64-bit) , but I keep running into issues. I’m using Python 3.13.0, and I’ve followed the instructions from the [documentation](https://pycddlib.readthedocs.io/en/latest/quickstart.html#installing-cddlib-and-gmp) to build it from source. Unfortunately, I’m still stuck with errors during the installation process.

<img width="616" alt="image" src="https://github.com/user-attachments/assets/2481ec64-ae34-48ef-8819-a66da6758314">

<img width="630" alt="image" src="https://github.com/user-attachments/assets/f9d56ec1-ca55-4fdf-a401-10e94435d2c9">

Could you please provide any advice or suggestions?
Thanks in advance!

Best regards,
Tamy

**Comment by mcmtroffaes** [comment]
Thanks for reporting.

From the messages, it appears as if the instructions weren't followed: one cannot build the Windows wheel with pip (due to limitations with pip itself; see the warning message in the documentation that you linked). You have to invoke "build" instead, from the source repository, to build the wheel locally, which you can then install with pip.

This said, I've just released a wheel for Python 3.13 on windows so a simple pip install should now work on that combination. Does that work for you?

**Comment by mcmtroffaes** [comment]
Closing; likely fixed with the newly released wheel. Feel free to reopen if that didn't solve the problem.
